services:
  # url-shortener-db service
  url-shortener-db:
    image: mongo:latest
    container_name: url-shortener-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: url_shortener
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet

  # url-shortener-be service
  url-shortener-be:
    image: url-shortener-be
    build:
      context: ./url-shortener-be
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        APP_PORT: 3000
        APP_PACKAGE_JSON_PATH: ./package.json
        DATABASE_URL: mongodb://admin:admin@url-shortener-db:27017/url_shortener?authSource=admin
        SHORTEN_BASE_URL: http://localhost:80/
        JWT_SECRET: some_secret
        JWT_EXPIRATION: 3600
        CLIENT_URL: http://localhost
    container_name: url-shortener-be
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - url-shortener-db

  # url-shortener-fe service
  url-shortener-fe:
    image: url-shortener-fe
    build:
      context: ./url-shortener-fe
      dockerfile: Dockerfile
      args:
        VITE_NODE_ENV: production
        VITE_SERVER_API_URL: http://localhost:3000
    container_name: url-shortener-fe
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - node_modules:/usr/src/app/node_modules

volumes:
  mongo-data:
    driver: local
  node_modules:
