@PORT = 3000
@HOST = http://localhost:{{PORT}}
@RESOURCE = /url
@URL = {{HOST}}{{RESOURCE}}
@CONTENT_TYPE_JSON = Content-Type: application/json
@AUTH_COOKIE = Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2NlZjM0NWVjZmViZTk4ODkzNmFkZWQiLCJpYXQiOjE3NDIxOTkyMjcsImV4cCI6MTc0MjIwMjgyN30.Int18PwC2ESvdOGcktixCcWnzYRPg0LyRJyEnXYuOW4; Max-Age=3600; Path=/; Expires=Mon, 17 Mar 2025 09:13:47 GMT; SameSite=Strict
@ID = 

### findMany
GET {{URL}}
{{CONTENT_TYPE_JSON}}

### findOneBySlug
GET {{URL}}/03a3d6s
{{CONTENT_TYPE_JSON}}

### createShort
POST {{URL}}
{{CONTENT_TYPE_JSON}}
{{AUTH_COOKIE}}

{
  "originalUrl": "https://nodejs.org/docs/latest/api/2"
}
