@PORT = 3000
@HOST = http://localhost:{{PORT}}
@RESOURCE = /users
@URL = {{HOST}}{{RESOURCE}}
@CONTENT_TYPE_JSON = Content-Type: application/json
@ID = 

### findMany
GET {{URL}}
{{CONTENT_TYPE_JSON}}

### create
POST {{URL}}
{{CONTENT_TYPE_JSON}}

{
  "email": "name2@company.com",
  "password": "raNdomPass1357!"
}
