services:
  # MongoDB service
  url-shortener-db:
    image: mongo:latest
    container_name: url-shortener-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: url_shortener
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet

  # url-shortener-be service
  url-shortener-be:
    image: url-shortener-be
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: url-shortener-be
    restart: no
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - APP_PACKAGE_JSON_PATH=./package.json
      - DATABASE_URL=mongodb://admin:admin@url-shortener-db:27017/url_shortener?authSource=admin
      - URL_SLUG_PREFIX=https://short.ly/
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - url-shortener-db
    command: npm run start:dev

volumes:
  mongo-data:
    driver: local
