@PORT = 3000
@HOST = http://localhost:{{PORT}}
@RESOURCE = /auth
@URL = {{HOST}}{{RESOURCE}}
@CONTENT_TYPE_JSON = Content-Type: application/json
@AUTH_COOKIE = Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2NlZjM0NWVjZmViZTk4ODkzNmFkZWQiLCJpYXQiOjE3NDE2OTQzNTAsImV4cCI6MTc0MTY5Nzk1MH0.hR0xRKkffNz3B9LVSAMIicCO7kpLLjEgjtyNfFPOw1w; Path=/; Expires=Wed, 12 Mar 2025 16:45:40 GMT; HttpOnly

### signup
POST {{URL}}/signup
{{CONTENT_TYPE_JSON}}

{
  "email": "name1@company.com",
  "password": "raNdomPass1357!"
}

### login
POST {{URL}}/login
{{CONTENT_TYPE_JSON}}

{
  "email": "name1@company.com",
  "password": "raNdomPass1357!"
}

### me
GET {{URL}}/me
{{CONTENT_TYPE_JSON}}
{{AUTH_COOKIE}}