@PORT = 3000
@HOST = http://localhost:{{PORT}}
@RESOURCE = /auth
@URL = {{HOST}}{{RESOURCE}}
@CONTENT_TYPE_JSON = Content-Type: application/json
@AUTH_COOKIE = Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2NlZjM0NWVjZmViZTk4ODkzNmFkZWQiLCJpYXQiOjE3NDE3ODY1NTAsImV4cCI6MTc0MTc5MDE1MH0.eCXILKd7DKvtuihr-o8WS4c-1ClmWaaz0fGEGFJES3o; Path=/; Expires=Tue, 18 Mar 2025 09:28:20 GMT; HttpOnly

### signup
POST {{URL}}/signup
{{CONTENT_TYPE_JSON}}

{
  "email": "name5@company.com",
  "password": "raNdomPass1357!"
}

### signin
POST {{URL}}/signin
{{CONTENT_TYPE_JSON}}

{
  "email": "name1@company.com",
  "password": "raNdomPass1357!"
}

### signout
POST {{URL}}/signout
{{CONTENT_TYPE_JSON}}
{{AUTH_COOKIE}}

### me
GET {{URL}}/me
{{CONTENT_TYPE_JSON}}
{{AUTH_COOKIE}}