@PORT = 3000
@HOST = http://localhost:{{PORT}}
@RESOURCE = /auth
@URL = {{HOST}}{{RESOURCE}}
@CONTENT_TYPE_JSON = Content-Type: application/json
@AUTH_COOKIE = Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2QxNzRhNTM5ZjVmZjhiZThlZjdlY2YiLCJpYXQiOjE3NDE3ODAxMzMsImV4cCI6MTc0MTc4MzczM30.BrMRUU43xy_f7udpJAkDf7d8yIGCzmEXnvIBQ67SmXs; Path=/; Expires=Tue, 18 Mar 2025 16:01:20 GMT; HttpOnly

### signup
POST {{URL}}/signup
{{CONTENT_TYPE_JSON}}

{
  "email": "name4@company.com",
  "password": "raNdomPass1357!"
}

### signin
POST {{URL}}/signin
{{CONTENT_TYPE_JSON}}

{
  "email": "name1@company.com",
  "password": "raNdomPass1357!"
}

### me
GET {{URL}}/me
{{CONTENT_TYPE_JSON}}
{{AUTH_COOKIE}}